{"name": "Ошибка при неверном пароле", "status": "passed", "description": "Проверяем, что нельзя авторизоваться с несуществующим паролем", "steps": [{"name": "Отправка запроса на авторизацию с несуществующим паролем", "status": "passed", "steps": [{"name": "Авторизация пользователя", "status": "passed", "parameters": [{"name": "email", "value": "'user_ed01db04@test.com'"}, {"name": "password", "value": "'nonepassword'"}], "start": 1757439462213, "stop": 1757439462828}], "start": 1757439462213, "stop": 1757439462828}, {"name": "Проверяем, что при создании пользователя без обязательного поля код ответ 401 и success: false", "status": "passed", "start": 1757439462828, "stop": 1757439462828}, {"name": "Проверяем что сообщение об ошибке: email or password are incorrect", "status": "passed", "start": 1757439462828, "stop": 1757439462828}], "start": 1757439462213, "stop": 1757439462829, "uuid": "7219aac2-425f-4912-9224-204f2a153b41", "historyId": "4b57dcbac64f372a558af3f3c4dbc79a", "testCaseId": "4b57dcbac64f372a558af3f3c4dbc79a", "fullName": "tests.test_auth_user.TestAuthUser#test_auth_user_invalid_password_failed", "labels": [{"name": "feature", "value": "API: Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_user"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "DESKTOP-RUV96V5"}, {"name": "thread", "value": "21508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_user"}]}